name: flutter_whatsapp
description: Flutter WhatsApp!

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.1.1
  dartz: ^0.8.9
  flutter_bloc: ^3.2.0
  get_it: ^4.0.0
  cached_network_image: ^2.0.0

  cupertino_icons: ^0.1.3
  feather_icons_flutter: ^4.7.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true